### ISSUE TITLE
exec format error

### ISSUE THREAD

**Issue by Jaskowicz1** [macOScontainers/rund#29]
When trying to follow the example, I get
```
[Warning] The requested image's platform (unknown) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

exec /bin/sh: exec format error
```

This is on a Mac mini M2. I am on Ventura

**Comment by Jaskowicz1** [comment]
> You don't need to uninstall, you can just temporarily quit it.

Hi there, I tried to quit it, didn't work. I then uninstalled it, reinstalled docker, did everything, it still shows the same issue.

**Comment by slonopotamus** [comment]
I'm not sure I can help you any further. If you're still getting exec error that talks about `linux`, it means you have something Linux-related running and it listens to `/var/lib/docker/dockerd.sock` socket file. And you just need to shut it down. The possibility of running macOS containers alongside with Linux containers is a dream of a _very_ far away future, so today we need to make conscious decisions on which one is currently in use.

**Comment by Jaskowicz1** [comment]
> I'm not sure I can help you any further. If you're still getting exec error that talks about `linux`, it means you have something Linux-related running (Docker Desktop, Rancher Desktop, colima, etc) and that listens to `/var/lib/docker/dockerd.sock` socket file, preventing macOS native Docker daemon from doing the same. And you just need to shut that software down. The possibility of running macOS containers alongside with Linux containers is a dream of a _very_ far away future, so today we need to make conscious decisions on which one is currently in use.

Ah yeah I replaced Docker Desktop with Colima as I couldn't figure out how to run Docker without (I just got this Mac about 10 hours ago haha, still getting used to this). I've stopped colima and docker seems to function now. It's reinstalling Ventura latest (though I have slow internet) so I'll update you on that asap.

In the mean time, do you mind telling me how you manage to get Docker running without colima/DD?

**Comment by slonopotamus** [comment]
Earthy has an [article that explains how all this macOS container stuff is functioning](https://earthly.dev/blog/macos-native-containers/). I'm not sure I would be able to explain things better than them :)

**Comment by Jaskowicz1** [comment]
> [Earthly](https://earthly.dev/) has an [article that explains how all this macOS container stuff is functioning](https://earthly.dev/blog/macos-native-containers/). I doubt I would be able to explain things better than them :)

This is a great link, thank you!

**Comment by Jaskowicz1** [comment]
I've got it alive! However, doing `RUN name -a` seems to infinitely build. Same goes for any run command. Any ideas?

**Comment by slonopotamus** [comment]
That was fixed yesterday: https://github.com/macOScontainers/rund/commit/cf7cb664cb88088dbf3cbaba23058fa60635176c

You need to `brew update && brew upgrade`

**Comment by slonopotamus** [comment]
Closing, since initial issue (exec format error) was resolved.

**Comment by Jaskowicz1** [comment]
That worked! Thank you!!!
