### ISSUE TITLE
[Question]: Not an issue, just a question 

### ISSUE THREAD

**Issue by jhay06** [macOScontainers/rund#34]
Yes , i installed the ventura container, and successfully run it from docker .
what now ?
 -  does it support gui ? 
 -  can we use xcode from the container ?

**Comment by slonopotamus** [comment]
Let's please not put all questions on earth in a single issue. That warning is harmless. See https://github.com/macOScontainers/macos-jail/issues/11. WRT amd64 - I don't have one, so can't debug why things do not work.
