### ISSUE TITLE
How can I exec a existed container which is running?

### ISSUE THREAD

**Issue by cavivie** [macOScontainers/rund#37]
Now, `docker attach <container_id>` can work, but `docker exec -it <container_id> /bin/bash` can not work, it shows a error:
`not implemented: unknown`

![image](https://github.com/macOScontainers/rund/assets/103884097/94c8a57f-cac6-43c5-948e-4ddf6ce65680)

**Comment by slonopotamus** [comment]
This is a good question! And indeed, relevant functionality is [not implemented yed](https://github.com/macOScontainers/rund/blob/0.0.6/containerd/service.go#L275).

**Comment by cavivie** [comment]
So we need to do something like [this](https://github.com/containerd/containerd/blob/main/cmd/containerd-shim-runc-v2/task/service.go#L260-L318), right?

**Comment by cavivie** [comment]
May I know if the reason why it has not been implemented here is that there are any technical restrictions or obstacles? I want to try to implement it.

**Comment by slonopotamus** [comment]
If you look  through `service.go`, there are multiple different API calls with `request.ExecID != ""` check. It needs investigation what each of them is supposed to do.

**Comment by slonopotamus** [comment]
Initial `docker exec` support was added in rund 0.0.7 (but there could be bugs).

**Comment by cavivie** [comment]
Thanks
