### ISSUE TITLE
Can this ever work without disabling SIP?

### ISSUE THREAD

**Issue by jlsalmon** [macOScontainers/rund#48]
Question in title. Security team aren't keen on disabling SIP on-premise, and also it can't be disabled on EC2 mac instances for example.

**Comment by slonopotamus** [comment]
Please, see #49. It might be possible to only requure disabling _part_ of SIP. But until SIP prevents `chroot` call, disabling of that part is unavoidable.

**Comment by jlsalmon** [comment]
Sorry, I totally missed #49!
